title: "Stichting Oekraïners in Nederland / Ukrainians in the Netherlands Foundation"
email: "support@ukrainians.nl"
corp-email: "donate@ukrainians.nl"
ext-rel-email: "externerelaties@ukrainians.nl"
description: >- # this means to ignore newlines until "baseurl:"
  Ukrainians in the Netherlands Foundation (Stichting Oekraïners in Nederland) is a non-profit platform established in 2014 to support the needs of the Dutch Ukrainian diaspora.
url: "https://ukrainians.nl"
baseurl: ""
facebook_url: https://www.facebook.com/OekrainersInNederland/
#twitter_url: TODO
linkedin_url: https://www.linkedin.com/company/stichting-oekra%C3%AFners-in-nederland
telegram_url: https://t.me/chat_ukrainians_nl
instagram_url: https://www.instagram.com/ukrainians__nl/
youtube_url: https://www.youtube.com/c/UkrainiansintheNetherlands/
github_url: https://github.com/ua-nl
keywords:
  - Stichting Oekraïners in Nederland
  - Ukrainians in the Netherlands Foundation
  - Фундація українці в Нідерландах
  - donate
  - donation
  - help
  - ukraine
  - netherlands
  - refugees
  - nl
  - charity
  - humanitarian
  - volunteer
  - aid
  - support
  - "2022"

phone: "+31102005661"

logo:
  en: "/assets/img/logo/logo-en.png"
  nl: "/assets/img/logo/logo-nl.png"
  ua: "/assets/img/logo/logo-ua.png"
logo-black:
  en: "/assets/img/logo/logo-en-black.png"
  nl: "/assets/img/logo/logo-nl-black.png"
  ua: "/assets/img/logo/logo-ua-black.png"
logo-white:
  en: "/assets/img/logo/logo-en-white.png"
  nl: "/assets/img/logo/logo-nl-white.png"
  ua: "/assets/img/logo/logo-ua-white.png"

permalink: "/:title"

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives

cover_image: "/assets/img/bg/page-title.png"

collections:
  features:
    output: true
  services:
    output: true

jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"

feed:
  collections:
    posts:
      path: "/index.xml"

exclude:
  - .git
  - .github
  - .gitignore
  - .jekyll-cache
  - .vscode
  - Gemfile
  - Gemfile.lock
  - Makefile
  - README.md
